
#include "wasmGlue.h"

#include <glue/class.h>
#include <glue/enum.h>
#include <TeosBase.h>
#include <TeosSea.h>
#include <TeosIce.h>

glue::MapValue wasmGlue() {
  // using namespace greeter;

  auto lib = glue::createAnyMap();

  // clang-format off
  
  lib["TeosBase"] = glue::createClass<TeosBase>()
    .addConstructor()
    .addMethod("gsw_Abs_Pressure_from_p", &TeosBase::gsw_Abs_Pressure_from_p)
    .addMethod("gsw_add_barrier", &TeosBase::gsw_add_barrier)
    .addMethod("gsw_add_mean", &TeosBase::gsw_add_mean)
    .addMethod("gsw_adiabatic_lapse_rate_from_t", &TeosBase::gsw_adiabatic_lapse_rate_from_t)
    .addMethod("gsw_adiabatic_lapse_rate_t_exact", &TeosBase::gsw_adiabatic_lapse_rate_t_exact)
    .addMethod("gsw_alpha", &TeosBase::gsw_alpha)
    .addMethod("gsw_alpha_CT_exact", &TeosBase::gsw_alpha_CT_exact)
    .addMethod("gsw_alpha_on_beta_CT_exact", &TeosBase::gsw_alpha_on_beta_CT_exact)
    .addMethod("gsw_alpha_wrt_CT_t_exact", &TeosBase::gsw_alpha_wrt_CT_t_exact)
    .addMethod("gsw_alpha_wrt_pt_t_exact", &TeosBase::gsw_alpha_wrt_pt_t_exact)
    .addMethod("gsw_Arsol", &TeosBase::gsw_Arsol)
    .addMethod("gsw_Arsol_SP_pt", &TeosBase::gsw_Arsol_SP_pt)
    .addMethod("gsw_atomic_weight", &TeosBase::gsw_atomic_weight)
    .addMethod("gsw_beta", &TeosBase::gsw_beta)
    .addMethod("gsw_beta_const_ct_t_exact", &TeosBase::gsw_beta_const_ct_t_exact)
    .addMethod("gsw_beta_const_pt_t_exact", &TeosBase::gsw_beta_const_pt_t_exact)
    .addMethod("gsw_chem_potential_relative_t_exact", &TeosBase::gsw_chem_potential_relative_t_exact)
    .addMethod("gsw_chem_potential_salt_t_exact", &TeosBase::gsw_chem_potential_salt_t_exact)
    .addMethod("gsw_chem_potential_water_t_exact", &TeosBase::gsw_chem_potential_water_t_exact)
    .addMethod("gsw_ct_first_derivatives_wrt_t_exact", &TeosBase::gsw_ct_first_derivatives_wrt_t_exact)
    .addMethod("gsw_ct_freezing", &TeosBase::gsw_ct_freezing)
    // .addMethod("gsw_CT_freezing", &TeosBase::gsw_CT_freezing) Not implemented fully in source
    .addMethod("gsw_ct_from_enthalpy", &TeosBase::gsw_ct_from_enthalpy)
    .addMethod("gsw_ct_from_enthalpy_exact", &TeosBase::gsw_ct_from_enthalpy_exact)
    .addMethod("gsw_ct_from_pt", &TeosBase::gsw_ct_from_pt)
    .addMethod("gsw_ct_from_t", &TeosBase::gsw_ct_from_t)
    .addMethod("gsw_ct_maxdensity", &TeosBase::gsw_ct_maxdensity)
    .addMethod("gsw_CT_maxdensity_exact", &TeosBase::gsw_CT_maxdensity_exact)
    .addMethod("gsw_deltasa_atlas", &TeosBase::gsw_deltasa_atlas)
    .addMethod("gsw_depth_from_z", &TeosBase::gsw_depth_from_z)
    .addMethod("gsw_dilution_coefficient_t_exact", &TeosBase::gsw_dilution_coefficient_t_exact)
    .addMethod("gsw_dynamic_enthalpy", &TeosBase::gsw_dynamic_enthalpy)
    .addMethod("gsw_dynamic_enthalpy_CT_exact", &TeosBase::gsw_dynamic_enthalpy_CT_exact)
    .addMethod("gsw_dynamic_enthalpy_t_exact", &TeosBase::gsw_dynamic_enthalpy_t_exact)
    .addMethod("gsw_enthalpy", &TeosBase::gsw_enthalpy)
    .addMethod("gsw_enthalpy_ct_exact", &TeosBase::gsw_enthalpy_ct_exact)
    .addMethod("gsw_enthalpy_diff_CT_exact", &TeosBase::gsw_enthalpy_diff_CT_exact)
    .addMethod("gsw_enthalpy_first_derivatives", &TeosBase::gsw_enthalpy_first_derivatives)
    .addMethod("gsw_enthalpy_first_derivatives_ct_exact", &TeosBase::gsw_enthalpy_first_derivatives_ct_exact)
    .addMethod("gsw_enthalpy_second_derivatives_ct_exact", &TeosBase::gsw_enthalpy_second_derivatives_ct_exact)
    .addMethod("gsw_enthalpy_sso_0", &TeosBase::gsw_enthalpy_sso_0)
    .addMethod("gsw_enthalpy_t_exact", &TeosBase::gsw_enthalpy_t_exact)
    .addMethod("gsw_entropy_first_derivatives", &TeosBase::gsw_entropy_first_derivatives)
    .addMethod("gsw_entropy_from_ct", &TeosBase::gsw_entropy_from_ct)
    .addMethod("gsw_entropy_part", &TeosBase::gsw_entropy_part)
    .addMethod("gsw_entropy_part_zerop", &TeosBase::gsw_entropy_part_zerop)
    .addMethod("gsw_entropy_second_derivatives", &TeosBase::gsw_entropy_second_derivatives)
    .addMethod("gsw_f", &TeosBase::gsw_f)
    .addMethod("gsw_fdelta", &TeosBase::gsw_fdelta)
    .addMethod("gsw_gibbs", &TeosBase::gsw_gibbs)
    .addMethod("gsw_Gibbs_energy_t_exact", &TeosBase::gsw_Gibbs_energy_t_exact)
    .addMethod("gsw_gibbs_ice", &TeosBase::gsw_gibbs_ice)
    .addMethod("gsw_gibbs_pt0_pt0", &TeosBase::gsw_gibbs_pt0_pt0)
    .addMethod("gsw_grav", &TeosBase::gsw_grav)
    .addMethod("gsw_Helmholtz_energy_t_exact", &TeosBase::gsw_Helmholtz_energy_t_exact)
    .addMethod("gsw_Hesol", &TeosBase::gsw_Hesol)
    .addMethod("gsw_Hesol_SP_pt", &TeosBase::gsw_Hesol_SP_pt)
    .addMethod("gsw_hill_ratio_at_sp2", &TeosBase::gsw_hill_ratio_at_sp2)
    // .addMethod("gsw_Hill_ratio_at_SP2", &TeosBase::gsw_Hill_ratio_at_SP2) Seems to be an error in code, looks like the capitals are different in c++ code. 
    .addMethod("gsw_internal_energy", &TeosBase::gsw_internal_energy)
    .addMethod("gsw_internal_energy_CT_exact", &TeosBase::gsw_internal_energy_CT_exact)
    // .addMethod("gsw_internal_energy_second_derivatives", &TeosBase::gsw_internal_energy_second_derivatives) Not implemented in source
    .addMethod("gsw_internal_energy_t_exact", &TeosBase::gsw_internal_energy_t_exact)
    .addMethod("gsw_isochoric_heat_cap_t_exact", &TeosBase::gsw_isochoric_heat_cap_t_exact)
    .addMethod("gsw_kappa", &TeosBase::gsw_kappa)
    .addMethod("gsw_kappa_const_t_exact", &TeosBase::gsw_kappa_const_t_exact)
    .addMethod("gsw_kappa_CT_exact", &TeosBase::gsw_kappa_CT_exact)
    .addMethod("gsw_kappa_t_exact", &TeosBase::gsw_kappa_t_exact)
    .addMethod("gsw_Krsol", &TeosBase::gsw_Krsol)
    .addMethod("gsw_Krsol_SP_pt", &TeosBase::gsw_Krsol_SP_pt)
    .addMethod("gsw_linear_interp_sa_ct", &TeosBase::gsw_linear_interp_sa_ct)
    .addMethod("gsw_linear_interp_sa_ct_for_dh", &TeosBase::gsw_linear_interp_sa_ct_for_dh)
    .addMethod("gsw_molality_from_SA", &TeosBase::gsw_molality_from_SA)
    .addMethod("gsw_N2sol", &TeosBase::gsw_N2sol)
    .addMethod("gsw_N2sol_SP_pt", &TeosBase::gsw_N2sol_SP_pt)
    .addMethod("gsw_N2Osol", &TeosBase::gsw_N2Osol)
    .addMethod("gsw_N2Osol_SP_pt", &TeosBase::gsw_N2Osol_SP_pt)
    .addMethod("gsw_Nsquared_lowerlimit", &TeosBase::gsw_Nsquared_lowerlimit)
    .addMethod("gsw_osmotic_coefficient_t_exact", &TeosBase::gsw_osmotic_coefficient_t_exact)
    .addMethod("gsw_osmotic_pressure_t_exact", &TeosBase::gsw_osmotic_pressure_t_exact)
    .addMethod("gsw_o2sol", &TeosBase::gsw_o2sol)
    .addMethod("gsw_o2sol_sp_pt", &TeosBase::gsw_o2sol_sp_pt)
    .addMethod("gsw_p_from_Abs_Pressure", &TeosBase::gsw_p_from_Abs_Pressure)
    .addMethod("gsw_p_from_z", &TeosBase::gsw_p_from_z)
    .addMethod("gsw_pchip_derivs", &TeosBase::gsw_pchip_derivs)
    .addMethod("gsw_pchip_edge_case", &TeosBase::gsw_pchip_edge_case)
    .addMethod("gsw_pot_enthalpy_from_pt", &TeosBase::gsw_pot_enthalpy_from_pt)
    .addMethod("gsw_pot_enthalpy_from_pt_ice", &TeosBase::gsw_pot_enthalpy_from_pt_ice)
    .addMethod("gsw_pot_enthalpy_from_specvol_ice_poly", &TeosBase::gsw_pot_enthalpy_from_specvol_ice_poly)
    .addMethod("gsw_pot_enthalpy_ice_freezing_first_derivatives_poly", &TeosBase::gsw_pot_enthalpy_ice_freezing_first_derivatives_poly)
    .addMethod("gsw_pot_enthalpy_ice_freezing_poly", &TeosBase::gsw_pot_enthalpy_ice_freezing_poly)
    .addMethod("gsw_pt_from_ct", &TeosBase::gsw_pt_from_ct)
    .addMethod("gsw_pt_from_t", &TeosBase::gsw_pt_from_t)
    .addMethod("gsw_pt0_from_t", &TeosBase::gsw_pt0_from_t)
    .addMethod("gsw_R_from_SP", &TeosBase::gsw_R_from_SP)
    .addMethod("gsw_rho", &TeosBase::gsw_rho)
    .addMethod("gsw_rho_alpha_beta", &TeosBase::gsw_rho_alpha_beta)
    .addMethod("gsw_rho_alpha_beta_indexed", &TeosBase::gsw_rho_alpha_beta_indexed)
    .addMethod("gsw_rho_first_derivatives_CT_exact", &TeosBase::gsw_rho_first_derivatives_CT_exact)
    .addMethod("gsw_rho_first_derivatives_wrt_enthalpy_CT_exact", &TeosBase::gsw_rho_first_derivatives_wrt_enthalpy_CT_exact)
    .addMethod("gsw_rho_second_derivatives_CT_exact", &TeosBase::gsw_rho_second_derivatives_CT_exact)
    // .addMethod("gsw_rho_second_derivatives_wrt_enthalpy_CT_exact", &TeosBase::gsw_rho_second_derivatives_wrt_enthalpy_CT_exact) Not implemented in source
    .addMethod("gsw_rr68_interp_section", &TeosBase::gsw_rr68_interp_section)
    .addMethod("gsw_rtIsNaN", &TeosBase::gsw_rtIsNaN)
    .addMethod("gsw_rtIsNaNF", &TeosBase::gsw_rtIsNaNF)
    .addMethod("gsw_saar", &TeosBase::gsw_saar)
    // .addMethod("gsw_SA_freezing_from_CT_poly", &TeosBase::gsw_SA_freezing_from_CT_poly) Not implemented in source, only in header definition.
    .addMethod("gsw_sa_from_sp", &TeosBase::gsw_sa_from_sp)
    .addMethod("gsw_sa_from_sp_baltic", &TeosBase::gsw_sa_from_sp_baltic)
    .addMethod("gsw_sa_from_sstar", &TeosBase::gsw_sa_from_sstar)
    .addMethod("gsw_sgn", &TeosBase::gsw_sgn)
    .addMethod("gsw_sp_from_c", &TeosBase::gsw_sp_from_c)
    .addMethod("gsw_SP_from_R", &TeosBase::gsw_SP_from_R)
    .addMethod("gsw_sp_from_sa", &TeosBase::gsw_sp_from_sa)
    .addMethod("gsw_sp_from_sa_baltic", &TeosBase::gsw_sp_from_sa_baltic)
    .addMethod("gsw_specvol", &TeosBase::gsw_specvol)
    .addMethod("gsw_specvol_alpha_beta_CT_exact", &TeosBase::gsw_specvol_alpha_beta_CT_exact)
    .addMethod("gsw_specvol_anom", &TeosBase::gsw_specvol_anom)
    .addMethod("gsw_specvol_anom_CT_exact", &TeosBase::gsw_specvol_anom_CT_exact)
    .addMethod("gsw_specvol_anom_standard_CT_exact", &TeosBase::gsw_specvol_anom_standard_CT_exact)
    .addMethod("gsw_specvol_anom_standard_t_exact", &TeosBase::gsw_specvol_anom_standard_t_exact)
    .addMethod("gsw_specvol_anom_t_exact", &TeosBase::gsw_specvol_anom_t_exact)
    .addMethod("gsw_specvol_CT_exact", &TeosBase::gsw_specvol_CT_exact)
    .addMethod("gsw_specvol_diff", &TeosBase::gsw_specvol_diff)
    .addMethod("gsw_specvol_first_derivatives_CT_exact", &TeosBase::gsw_specvol_first_derivatives_CT_exact)
    .addMethod("gsw_specvol_first_derivatives_wrt_enthalpy_CT_exact", &TeosBase::gsw_specvol_first_derivatives_wrt_enthalpy_CT_exact)
    .addMethod("gsw_specvol_from_pot_enthalpy_ice_first_derivatives_poly", &TeosBase::gsw_specvol_from_pot_enthalpy_ice_first_derivatives_poly)
    .addMethod("gsw_specvol_from_pot_enthalpy_ice_poly", &TeosBase::gsw_specvol_from_pot_enthalpy_ice_poly)
    .addMethod("gsw_specvol_p_parts", &TeosBase::gsw_specvol_p_parts)
    .addMethod("gsw_specvol_second_derivatives_CT_exact", &TeosBase::gsw_specvol_second_derivatives_CT_exact)
    .addMethod("gsw_specvol_t_exact", &TeosBase::gsw_specvol_t_exact)
    .addMethod("gsw_specvol_sso_0", &TeosBase::gsw_specvol_sso_0)
    .addMethod("gsw_sr_from_sp", &TeosBase::gsw_sr_from_sp)
    // .addMethod("gsw_SSO", &TeosBase::gsw_SSO) Dosent seem to be implemented in c++ code
    .addMethod("gsw_sstar_from_sa", &TeosBase::gsw_sstar_from_sa)
    .addMethod("gsw_sstar_from_sp", &TeosBase::gsw_sstar_from_sp)
    .addMethod("gsw_sum", &TeosBase::gsw_sum)
    .addMethod("gsw_t_deriv_chem_potential_water_t_exact", &TeosBase::gsw_t_deriv_chem_potential_water_t_exact)
    .addMethod("gsw_t_freezing", &TeosBase::gsw_t_freezing)
    .addMethod("gsw_t_from_ct", &TeosBase::gsw_t_from_ct)
    .addMethod("gsw_t_from_pt0", &TeosBase::gsw_t_from_pt0)
    .addMethod("gsw_t_maxdensity_exact", &TeosBase::gsw_t_maxdensity_exact)
    .addMethod("gsw_t90_from_t48", &TeosBase::gsw_t90_from_t48)
    .addMethod("gsw_t90_from_t68", &TeosBase::gsw_t90_from_t68)
    .addMethod("gsw_util_indx", &TeosBase::gsw_util_indx)
    .addMethod("gsw_util_sort_dbl", &TeosBase::gsw_util_sort_dbl)
    .addMethod("gsw_util_xinterp1", &TeosBase::gsw_util_xinterp1)
    .addMethod("gsw_weighted_nanmean", &TeosBase::gsw_weighted_nanmean)
    .addMethod("gsw_z_from_depth", &TeosBase::gsw_z_from_depth)
    .addMethod("gsw_z_from_p", &TeosBase::gsw_z_from_p)   
  ;

  lib["TeosSea"] = glue::createClass<TeosSea>()
    .addConstructor()
    .addMethod("gsw_adiabatic_lapse_rate_from_ct", &TeosSea::gsw_adiabatic_lapse_rate_from_ct)
    .addMethod("gsw_alpha_on_beta", &TeosSea::gsw_alpha_on_beta)
    .addMethod("gsw_alpha_wrt_t_exact", &TeosSea::gsw_alpha_wrt_t_exact)
    .addMethod("gsw_beta_const_t_exact", &TeosSea::gsw_beta_const_t_exact)
    .addMethod("gsw_cabbeling", &TeosSea::gsw_cabbeling)
    .addMethod("gsw_cabbeling_ct_exact", &TeosSea::gsw_cabbeling_ct_exact)
    .addMethod("gsw_c_from_sp", &TeosSea::gsw_c_from_sp)
    .addMethod("gsw_cp_t_exact", &TeosSea::gsw_cp_t_exact)
    .addMethod("gsw_ct_from_entropy", &TeosSea::gsw_ct_from_entropy)
    .addMethod("gsw_ct_from_rho_exact", &TeosSea::gsw_ct_from_rho_exact)
    .addMethod("gsw_ct_first_derivatives", &TeosSea::gsw_ct_first_derivatives)
    .addMethod("gsw_ct_second_derivatives", &TeosSea::gsw_ct_second_derivatives)
    .addMethod("gsw_enthalpy_first_derivatives_wrt_t_exact", &TeosSea::gsw_enthalpy_first_derivatives_wrt_t_exact)
    .addMethod("gsw_enthalpy_second_derivatives", &TeosSea::gsw_enthalpy_second_derivatives)
    .addMethod("gsw_entropy_from_pt", &TeosSea::gsw_entropy_from_pt)
    .addMethod("gsw_entropy_from_t", &TeosSea::gsw_entropy_from_t)
    // .addMethod("gsw_geo_strf_dyn_height", &TeosSea::gsw_geo_strf_dyn_height) # Currently contains errors TODO: Look into @zacpullen
    // .addMethod("gsw_geo_strf_dyn_height_1", &TeosSea::gsw_geo_strf_dyn_height_1)
    .addMethod("gsw_internal_energy_first_derivatives", &TeosSea::gsw_internal_energy_first_derivatives)
    .addMethod("gsw_internal_energy_first_derivatives_ct_exact", &TeosSea::gsw_internal_energy_first_derivatives_ct_exact)
    .addMethod("gsw_internal_energy_second_derivatives", &TeosSea::gsw_internal_energy_second_derivatives)
    .addMethod("gsw_isopycnal_slope_ratio", &TeosSea::gsw_isopycnal_slope_ratio)
    .addMethod("gsw_latentheat_evap_ct", &TeosSea::gsw_latentheat_evap_ct)
    .addMethod("gsw_latentheat_evap_t", &TeosSea::gsw_latentheat_evap_t)
    // .addMethod("gsw_linear_interp_SA_CT_for_dh", &TeosSea::gsw_linear_interp_SA_CT_for_dh)
    .addMethod("gsw_ntp_pt_vs_CT_ratio", &TeosSea::gsw_ntp_pt_vs_CT_ratio)
    .addMethod("gsw_p_sequence", &TeosSea::gsw_p_sequence)
    .addMethod("gsw_pot_rho_t_exact", &TeosSea::gsw_pot_rho_t_exact)
    .addMethod("gsw_pt_first_derivatives", &TeosSea::gsw_pt_first_derivatives)
    .addMethod("gsw_pt_from_entropy", &TeosSea::gsw_pt_from_entropy)
    .addMethod("gsw_pt_second_derivatives", &TeosSea::gsw_pt_second_derivatives)
    .addMethod("gsw_refine_grid_for_dh", &TeosSea::gsw_refine_grid_for_dh)
    .addMethod("gsw_rho_alpha_beta_ct_exact", &TeosSea::gsw_rho_alpha_beta_ct_exact)
    .addMethod("gsw_rho_ct_exact", &TeosSea::gsw_rho_ct_exact)
    .addMethod("gsw_rho_second_derivatives", &TeosSea::gsw_rho_second_derivatives)
    .addMethod("gsw_rho_first_derivatives", &TeosSea::gsw_rho_first_derivatives)
    .addMethod("gsw_rho_first_derivatives_wrt_enthalpy", &TeosSea::gsw_rho_first_derivatives_wrt_enthalpy)
    .addMethod("gsw_rho_second_derivatives_wrt_enthalpy", &TeosSea::gsw_rho_second_derivatives_wrt_enthalpy)
    .addMethod("gsw_rho_t_exact", &TeosSea::gsw_rho_t_exact)
    .addMethod("gsw_rr68_interp_sa_ct", &TeosSea::gsw_rr68_interp_sa_ct)
    .addMethod("gsw_sa_from_rho", &TeosSea::gsw_sa_from_rho)
    .addMethod("gsw_sigma0", &TeosSea::gsw_sigma0)
    .addMethod("gsw_sigma0_ct_exact", &TeosSea::gsw_sigma0_ct_exact)
    .addMethod("gsw_sigma0_pt0_exact", &TeosSea::gsw_sigma0_pt0_exact)
    .addMethod("gsw_sigma1", &TeosSea::gsw_sigma1)
    .addMethod("gsw_sigma1_ct_exact", &TeosSea::gsw_sigma1_ct_exact)
    .addMethod("gsw_sigma2", &TeosSea::gsw_sigma2)
    .addMethod("gsw_sigma2_ct_exact", &TeosSea::gsw_sigma2_ct_exact)
    .addMethod("gsw_sigma3", &TeosSea::gsw_sigma3)
    .addMethod("gsw_sigma3_ct_exact", &TeosSea::gsw_sigma3_ct_exact)
    .addMethod("gsw_sigma4", &TeosSea::gsw_sigma4)
    .addMethod("gsw_sigma4_ct_exact", &TeosSea::gsw_sigma4_ct_exact)
    .addMethod("gsw_sound_speed", &TeosSea::gsw_sound_speed)
    .addMethod("gsw_sound_speed_ct_exact", &TeosSea::gsw_sound_speed_ct_exact)
    .addMethod("gsw_sound_speed_t_exact", &TeosSea::gsw_sound_speed_t_exact)
    .addMethod("gsw_sp_from_sk", &TeosSea::gsw_sp_from_sk)
    .addMethod("gsw_sp_from_sr", &TeosSea::gsw_sp_from_sr)
    .addMethod("gsw_sp_from_sstar", &TeosSea::gsw_sp_from_sstar)
    .addMethod("gsw_sp_salinometer", &TeosSea::gsw_sp_salinometer)
    .addMethod("gsw_specvol_alpha_beta", &TeosSea::gsw_specvol_alpha_beta)
    .addMethod("gsw_specvol_anom_standard", &TeosSea::gsw_specvol_anom_standard)
    .addMethod("gsw_specvol_first_derivatives", &TeosSea::gsw_specvol_first_derivatives)
    .addMethod("gsw_specvol_first_derivatives_wrt_enthalpy", &TeosSea::gsw_specvol_first_derivatives_wrt_enthalpy)
    .addMethod("gsw_specvol_second_derivatives", &TeosSea::gsw_specvol_second_derivatives)
    .addMethod("gsw_specvol_second_derivatives_wrt_enthalpy", &TeosSea::gsw_specvol_second_derivatives_wrt_enthalpy)
    .addMethod("gsw_spiciness0", &TeosSea::gsw_spiciness0)
    .addMethod("gsw_spiciness1", &TeosSea::gsw_spiciness1)
    .addMethod("gsw_spiciness2", &TeosSea::gsw_spiciness2)
    .addMethod("gsw_t_from_entropy", &TeosSea::gsw_t_from_entropy)
    .addMethod("gsw_t_from_rho_exact", &TeosSea::gsw_t_from_rho_exact)
    .addMethod("gsw_thermobaric", &TeosSea::gsw_thermobaric)
    .addMethod("gsw_thermobaric_ct_exact", &TeosSea::gsw_thermobaric_ct_exact)
    .addMethod("gsw_turner_rsubrho", &TeosSea::gsw_turner_rsubrho)
    .addMethod("gsw_util_interp1q_int", &TeosSea::gsw_util_interp1q_int)
    .addMethod("gsw_util_linear_interp", &TeosSea::gsw_util_linear_interp)
    .addMethod("gsw_util_pchip_interp", &TeosSea::gsw_util_pchip_interp);

  lib["TeosIce"] = glue::createClass<TeosIce>()
    .addConstructor()
    .addMethod("gsw_adiabatic_lapse_rate_ice", &TeosIce::gsw_adiabatic_lapse_rate_ice)
    .addMethod("gsw_alpha_wrt_t_ice", &TeosIce::gsw_alpha_wrt_t_ice)
    .addMethod("gsw_chem_potential_water_ice", &TeosIce::gsw_chem_potential_water_ice)
    .addMethod("gsw_cp_ice", &TeosIce::gsw_cp_ice)
    .addMethod("gsw_ct_freezing_exact", &TeosIce::gsw_ct_freezing_exact)
    .addMethod("gsw_ct_freezing_first_derivatives", &TeosIce::gsw_ct_freezing_first_derivatives)
    .addMethod("gsw_ct_freezing_first_derivatives_poly", &TeosIce::gsw_ct_freezing_first_derivatives_poly)
    .addMethod("gsw_ct_freezing_poly", &TeosIce::gsw_ct_freezing_poly)
    .addMethod("gsw_ct_from_rho", &TeosIce::gsw_ct_from_rho)
    .addMethod("gsw_deltasa_from_sp", &TeosIce::gsw_deltasa_from_sp)
    .addMethod("gsw_enthalpy_diff", &TeosIce::gsw_enthalpy_diff)
    .addMethod("gsw_enthalpy_ice", &TeosIce::gsw_enthalpy_ice)
    .addMethod("gsw_entropy_ice", &TeosIce::gsw_entropy_ice)
    .addMethod("gsw_frazil_properties", &TeosIce::gsw_frazil_properties)
    .addMethod("gsw_frazil_properties_potential", &TeosIce::gsw_frazil_properties_potential)
    .addMethod("gsw_frazil_properties_potential_poly", &TeosIce::gsw_frazil_properties_potential_poly)
    .addMethod("gsw_frazil_ratios_adiabatic", &TeosIce::gsw_frazil_ratios_adiabatic)
    .addMethod("gsw_frazil_ratios_adiabatic_poly", &TeosIce::gsw_frazil_ratios_adiabatic_poly)
    .addMethod("gsw_geo_strf_dyn_height_pc", &TeosIce::gsw_geo_strf_dyn_height_pc)
    .addMethod("gsw_gibbs_ice_part_t", &TeosIce::gsw_gibbs_ice_part_t)
    .addMethod("gsw_gibbs_ice_pt0", &TeosIce::gsw_gibbs_ice_pt0)
    .addMethod("gsw_gibbs_ice_pt0_pt0", &TeosIce::gsw_gibbs_ice_pt0_pt0)
    .addMethod("gsw_helmholtz_energy_ice", &TeosIce::gsw_helmholtz_energy_ice)
    .addMethod("gsw_ice_fraction_to_freeze_seawater", &TeosIce::gsw_ice_fraction_to_freeze_seawater)
    .addMethod("gsw_internal_energy_ice", &TeosIce::gsw_internal_energy_ice)
    .addMethod("gsw_ipv_vs_fnsquared_ratio", &TeosIce::gsw_ipv_vs_fnsquared_ratio)
    .addMethod("gsw_kappa_const_t_ice", &TeosIce::gsw_kappa_const_t_ice)
    .addMethod("gsw_kappa_ice", &TeosIce::gsw_kappa_ice)
    .addMethod("gsw_latentheat_melting", &TeosIce::gsw_latentheat_melting)
    .addMethod("gsw_melting_ice_equilibrium_sa_ct_ratio", &TeosIce::gsw_melting_ice_equilibrium_sa_ct_ratio)
    .addMethod("gsw_melting_ice_equilibrium_sa_ct_ratio_poly", &TeosIce::gsw_melting_ice_equilibrium_sa_ct_ratio_poly)
    .addMethod("gsw_melting_ice_into_seawater", &TeosIce::gsw_melting_ice_into_seawater)
    .addMethod("gsw_melting_ice_sa_ct_ratio", &TeosIce::gsw_melting_ice_sa_ct_ratio)
    .addMethod("gsw_melting_ice_sa_ct_ratio_poly", &TeosIce::gsw_melting_ice_sa_ct_ratio_poly)
    .addMethod("gsw_melting_seaice_equilibrium_sa_ct_ratio", &TeosIce::gsw_melting_seaice_equilibrium_sa_ct_ratio)
    .addMethod("gsw_melting_seaice_equilibrium_sa_ct_ratio_poly", &TeosIce::gsw_melting_seaice_equilibrium_sa_ct_ratio_poly)
    .addMethod("gsw_melting_seaice_into_seawater", &TeosIce::gsw_melting_seaice_into_seawater)
    .addMethod("gsw_melting_seaice_sa_ct_ratio", &TeosIce::gsw_melting_seaice_sa_ct_ratio)
    .addMethod("gsw_melting_seaice_sa_ct_ratio_poly", &TeosIce::gsw_melting_seaice_sa_ct_ratio_poly)
    .addMethod("gsw_nsquared", &TeosIce::gsw_nsquared)
    .addMethod("gsw_pot_enthalpy_ice_freezing", &TeosIce::gsw_pot_enthalpy_ice_freezing)
    .addMethod("gsw_pot_enthalpy_ice_freezing_first_derivatives", &TeosIce::gsw_pot_enthalpy_ice_freezing_first_derivatives)
    .addMethod("gsw_pot_enthalpy_from_pt_ice_poly", &TeosIce::gsw_pot_enthalpy_from_pt_ice_poly)
    .addMethod("gsw_pot_enthalpy_from_specvol_ice", &TeosIce::gsw_pot_enthalpy_from_specvol_ice)
    // .addMethod("gsw_pressure_coefficient_ice", &TeosIce::gsw_pressure_coefficient_ice)
    .addMethod("gsw_pressure_freezing_ct", &TeosIce::gsw_pressure_freezing_ct)
    .addMethod("gsw_pt_from_pot_enthalpy_ice", &TeosIce::gsw_pt_from_pot_enthalpy_ice)
    .addMethod("gsw_pt_from_pot_enthalpy_ice_poly", &TeosIce::gsw_pt_from_pot_enthalpy_ice_poly)
    .addMethod("gsw_pt_from_pot_enthalpy_ice_poly_dh", &TeosIce::gsw_pt_from_pot_enthalpy_ice_poly_dh)
    .addMethod("gsw_pt_from_t_ice", &TeosIce::gsw_pt_from_t_ice)
    .addMethod("gsw_pt0_cold_ice_poly", &TeosIce::gsw_pt0_cold_ice_poly)
    .addMethod("gsw_rho_ice", &TeosIce::gsw_rho_ice)
    .addMethod("gsw_sa_freezing_estimate", &TeosIce::gsw_sa_freezing_estimate)
    .addMethod("gsw_sa_freezing_from_ct", &TeosIce::gsw_sa_freezing_from_ct)
    .addMethod("gsw_sa_freezing_from_ct_poly", &TeosIce::gsw_sa_freezing_from_ct_poly)
    .addMethod("gsw_sa_freezing_from_t", &TeosIce::gsw_sa_freezing_from_t)
    .addMethod("gsw_sa_freezing_from_t_poly", &TeosIce::gsw_sa_freezing_from_t_poly)
    .addMethod("gsw_sa_p_inrange", &TeosIce::gsw_sa_p_inrange)
    .addMethod("gsw_seaice_fraction_to_freeze_seawater", &TeosIce::gsw_seaice_fraction_to_freeze_seawater)
    .addMethod("gsw_specvol_from_pot_enthalpy_ice", &TeosIce::gsw_specvol_from_pot_enthalpy_ice)
    .addMethod("gsw_specvol_ice", &TeosIce::gsw_specvol_ice)
    .addMethod("gsw_sound_speed_ice", &TeosIce::gsw_sound_speed_ice)
    .addMethod("gsw_pt0_from_t_ice", &TeosIce::gsw_pt0_from_t_ice)
    .addMethod("gsw_t_freezing_exact", &TeosIce::gsw_t_freezing_exact)
    .addMethod("gsw_t_freezing_first_derivatives", &TeosIce::gsw_t_freezing_first_derivatives)
    .addMethod("gsw_t_freezing_first_derivatives_poly", &TeosIce::gsw_t_freezing_first_derivatives_poly)
    // .addMethod("gsw_t_freezing_poly", &TeosIce::gsw_t_freezing_poly)
    // .addMethod("gsw_t_freezing_poly", &TeosIce::gsw_t_freezing_poly)
    .addMethod("gsw_t_from_pt0_ice", &TeosIce::gsw_t_from_pt0_ice)
    .addMethod("gsw_t_from_rho_ice", &TeosIce::gsw_t_from_rho_ice)
  ;


  // clang-format on

  return lib;
}
